language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DV=1.8.14
  - DV=1.9.9
  - DV=1.10
install:
  - pip install Django==$DV
  - pip install -e .
script:
  - ./run_tests.sh
notifications:
  email:
    - ci@callowayproject.com
